name: Fizzbuzz
on: [push]
jobs:
  build:
    name: Build (Unit tests)
    runs-on: ubuntu-latest


    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: yarn

      - name: Execute tests
        # Runs a script that creates a PostgreSQL client, populates
        # the client with data, and retrieves data
        run: yarn test

